database:
  driver: "sqlite"
  dbname: "database_name"
  username: "user"
  password: "password"
  host: "localhost"
  port: "5432"
  logmode: true

server:
  port: "8081"
  secret: "mySecretKey"
  accessTokenExpireDuration: 1 
  refreshTokenExpireDuration: 1
  limitCountPerRequest: 1 