host: localhost:8081
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GO Swagger Example API
  version: "1.0"
paths:
  /auth/check:
    post:
      consumes:
      - application/json
      description: CheckToken header example
      parameters:
      - default: Bearer <Add access token here>
        description: Insert your access token
        in: header
        name: Token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: success
      security:
      - ApiKeyAuth: []
      summary: CheckToken
      tags:
      - auth
  /auth/refresh:
    post:
      consumes:
      - application/json
      description: RefreshToken Process
      parameters:
      - description: RefreshToken
        in: body
        name: RefreshToken
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Refresh Token
      tags:
      - auth
  /auth/signin:
    post:
      consumes:
      - application/json
      description: Signin Process
      parameters:
      - description: Signin
        in: body
        name: Signin
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Signin
      tags:
      - auth
  /posts/:
    get:
      consumes:
      - application/json
      description: get posts
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: List posts
      tags:
      - posts
    post:
      consumes:
      - application/json
      description: Create Post
      parameters:
      - description: Post
        in: body
        name: Post
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Create Post
      tags:
      - posts
  /posts/{id}:
    delete:
      consumes:
      - application/json
      description: Delete Post
      operationId: get-string-by-int
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Delete Post
      tags:
      - posts
    get:
      consumes:
      - application/json
      description: get by ID
      operationId: get-string-by-int
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Show a Post
      tags:
      - posts
    put:
      consumes:
      - application/json
      description: Update Post
      parameters:
      - description: Post ID
        in: path
        name: id
        required: true
        type: integer
      - description: Post
        in: body
        name: Post
        required: true
        schema:
          type: object
      produces:
      - application/json
      responses:
        "200":
          description: Success
      summary: Update Post
      tags:
      - posts
swagger: "2.0"
